# Generated by Django 4.0.3 on 2023-05-07 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group5', '0002_cartitem_restaurant_food_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='active',
        ),
    ]
