# Generated by Django 4.0.3 on 2023-05-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group5', '0003_remove_cartitem_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='map_src',
            field=models.TextField(default='NULL'),
            preserve_default=False,
        ),
    ]
