# Generated by Django 4.0.3 on 2023-05-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group5', '0004_restaurant_map_src'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
