# Generated by Django 4.0.3 on 2023-05-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group5', '0006_alter_question_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='district',
            field=models.CharField(max_length=100),
        ),
    ]
